---
title: "child_doc.Rmd"
---

A Amazônia Legal é atualmente composta por nove unidades federativas do Brasil e ocupa aproximadamente 59,9% do território nacional. Abrangendo toda a porção brasileira do bioma Amazônia, a Amazônia Legal engloba ainda cerca de 20% do bioma Cerrado e parte do Pantanal, abrigando grande variedade de ecossistemas com diferentes tipos de vegetação, clima e solo [@fearnside1995,@ibge2021]. Frente a intensa pressão sobre essas áreas, devido ao desmatamento ilegal, o avanço da urbanização e a expansão de fronteiras agrícolas, é colocado em evidência a importância da conservação estratégica e o respeito a legislação ambiental [@kanieski2012,@dantas2020]. 

O licenciamento ambiental é um dos mais importantes instrumentos do Estado no que se refere a políticas ambientais, empregado no gerenciamento de atividades econômicas diretamente ligadas aos recursos naturais e a comunidade. Amparado pela Constituição Federal brasileira de 1988 e pela Lei 6.938/81 [@brasil1981], o licenciamento ambiental tem como principal orientação às Resoluções CONAMA 001/86, 237/97 [@brasil1997] e à Lei Complementar nº 140/2011 [@brasil2011]. 

Anteriormente de total competência da extinta Secretaria Especial de Meio Ambiente da Presidência da República (SEMA/PR - 1973-1989), a partir de seu fechamento, os processos de licenciamento ambiental passaram a ser de total responsabilidade do então recém-criado Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis (IBAMA). Com isso, todo e qualquer empreendimento ligado ao manejo de recursos naturais, necessitam anteriormente ao início de suas atividades receberem a aprovação do órgão.
 
De acordo com a Instrução Normativa nº 5, de 11 de dezembro de 2006, ao solicitar a elaboração de um Plano de Manejo Florestal Sustentável (PMFS) em área de abrangência da Amazônia Legal, tem-se o Inventário Florestal como um dos documentos obrigatórios a serem apresentados ao órgão ambiental, de onde serão extraídas informações referentes a estrutura e dinâmica da floresta, servindo como base para a prescrição de parâmetros importantes no processo de  regulação da produção floresta, como: intensidade de corte, diâmetro mínimo de corte, lista das espécies autorizadas e limite de árvores a serem abatidas por hectare (IBAMA, 2006)[@brasil2006]. Desse modo, fica clara a importância de se realizar a auditoria dos inventários florestais apresentados durante os processos de solicitação do PMFS. 

No entanto, devido à extensão territorial que a Amazônia legal possui e às diferentes características observadas em cada região, a realização de fiscalizações e auditorias in loco com regularidade e frequência em todas as áreas de PMFS têm se mostrado inviável. Situação agravada pelos baixos recursos que os órgãos responsáveis por essa tarefa possuem, prejudicando muito a ação do governo no combate às irregularidades [@stone1998, @dittmar2011].

Nos últimos anos as metodologias referentes as etapas que envolvem o inventário florestal têm apresentado constate evolução, desde a sua fase de campo durante a coleta de informações com o emprego de geotecnologias, como imagens de satélite [@silveira2023], dados LiDAR [@queinnec2022], fotogrametria [@piermattei2019] e mais recentemente a tecnologia KATAM [@holcomb2021], como também, durante a fase de processamento dos dados com o emprego de Machine Learning [@bayat2021]. 

O emprego de novas tecnologias nas etapas de coleta e processamento de dados de inventários florestais são de grande importância para o setor, pois resultam em menor esforço amostral e consequentemente no tempo e custo de operação, além do aumento no nível de precisão dos resultados [@bayat2021, @queinnec2022]. Essa mesma evolução não é observada para a etapa de auditoria de inventários florestais, sendo essa, uma das mais importantes dentro de todo processo, pois a partir dela podemos inferir a real qualidade dos dados apresentados previamente [@attie2000].

Até o momento, as metodologias para auditoria de inventários florestais adotadas por empresas e órgão ambienteis baseiam-se em remedições de uma porcentagem das parcelas mensuradas e posterior comparação de desvios de medições entre os inventários apresentados e os inventários auditados [@timber2015, @fischer2019]. No entanto, tais metodologias demandam uma intensa agenda de visitas in loco e uma complexa logística para o planejamento das atividades [@campos2017]. 

Uma alternativa é a criação de uma metodologia que identifique e classifique os inventários florestais que apresentem indícios de fraudes por meio do reconhecimento de padrões. As fiscalizações e auditorias de processos por meio da mineração de grandes bases de dados buscando identificar indícios de erros, fraudes ou anomalias, tem se mostrado eficientes em diferentes áreas. Um exemplo é a detecção de fraudes em transações de cartões de crédito [@coelho2006], em campanhas eleitorais [@tam2007], em investigações de lavagem de dinheiro [@silva2014], entre outras. 

Nesse cenário, o emprego de métodos probabilísticos como modelos baseados em estatística Bayesiana, se justificam pela baixa complexidade e alta eficiência, quando aliados a uma base de dados adequada [@bolstad2016]. A estatística Bayesiana baseia-se no teorema de Bayes, no qual a distribuição a priori fornece informações prévia sobre a variável estudada, antes mesmo da observação dos dados [@da2012]. A influência da nova informação observada será estabelecida pela função de verossimilhança para se obter uma distribuição a posteriori.

Diante disso, o presente estudo visa propor a distribuição a priori para diferentes padrões observados nos dados de inventários florestais, que servirão de referência para o cálculo da probabilidade condicional usando atualização Bayesiana.  
