---
title: "Discussão"
output: html_document
---

A aplicação da estatística descritiva aos dados de DAP resultou predominantemente em curvas de distribuição do tipo leptocúrtica e forma altamente assimétrica positiva (direita). Isto indica uma maior frequência de valores distantes da média [@marangon2016], configurando a presença de poucos fragmentos com indivíduos que apresentam valores muito elevados, validando a classificação de distribuição exponencial para grande parte dos indicadores. 

Com o ajuste do modelo de Meyer aos 36 inventários presentes na base de dados, foram encontrados valores médios para o intercepto (β0) e coeficiente angular (β1) de 4,8547 e -0,0512, respectivamente, bem como q de Lioncourt (q) médio de 2,4467. Souza, et al. (2006), trabalhando com diferentes espécies em uma floresta de terra firme, no município de Paragominas, Pará, encontraram valores de 6,698 (Classe I), 6,566 (Classe II), 6,630 (Classe III) para o β0 e valores de -0,073 (Classe I), -0,069 (Classe II), -0,071 (Classe III) para o β1. Reis et al. (2014), analisando a dinâmica da distribuição diamétrica entre 1997 e 2010 de algumas espécies de sapotácea na Amazônia, encontraram valores de q de Lioncourt de 1,88 antes da exploração, 1,97 pós exploração e 1,89 13 anos após a exploração. 

É comum que ocorram variações na distribuição diamétrica [@dantas2020] e nos valores obtidos para o q de Lioncourt entre os diferentes tipos de florestas, devido a fatores como, a ecologia, herbívora, ação antrópica, dentre outros [@daCosta2019]. No entanto, vale ressaltar, que em todas as ocasiões os resultados obtidos pelos autores se encontram dentro do intervalo apresentado no presente trabalho. É fundamental entender a estrutura de uma floresta através da avaliação da distribuição diamétrica, pois é possível inferir sobre o ingresso, mortalidade e a dinâmica de crescimento das espécies presentes na área [@reis2014]. 

Através da análise do modelo matemático de Benford (1938), aplicado aos dados de DAP, distribuição das famílias, gêneros e espécies, foi constatado que apenas o indicador referente aos dois primeiros dígitos do DAP apresentou conformidade, de acordo com o valor do Desvio Absoluto Médio, como descrito por Nigrini (2012). No entanto, vale ressaltar que a não compatibilidade dos dados com a distribuição de Benford também pode ser utilizada como indicador de desvio [@bonach2009]. É de se esperar a não ocorrência da lei de Benford, uma vez que a definição de valor mínimo de inclusão para o DAP a ser mensurado, prejudica a aleatoriedade dos dados de diâmetro do inventário. 

A análise de densidade de Kernel tem se tornado uma importante ferramenta em estudos que envolvem análise da distribuição espacial de espécies [@oliveira2021], análise do desmatamento [@chen2021] e focos de incêndios [@barbosa2021]. No presente estudo, com a análise de densidade de Kernel aplicada aos dados foi obtido um padrão de distribuição do número de espécies, gêneros e famílias presentes em cada inventário amostrado. O parâmetro BW foi dimensionado de modo que o mesmo representasse o desvio padrão de Kernel. Com isso, entende-se que a maior variação entre os indivíduos observados nos 36 inventários amostrados ocorre para a classe Família, ou seja, a distribuição do número de famílias não ocorre de forma homogenia dentro da área da Amazônia legal. Esses resultados são justificados pelo fato dessa área englobar parte do bioma Amazônia, além de aproximadamente 20% do bioma Cerrado e parte do Pantanal, abrigando grande variedade de ecossistemas com diferentes tipos de vegetações [@fearnside1995, @ibge2021_2].

Quando comparado os valores de frequência relativa, dominância relativa e densidade relativa aplicada as espécies citadas por de Lima, et al. (2022), com trabalhos desenvolvidos na região da Amazônia Legal [@gama2002, @oliveira2008, @alves2008, @batista2015], é observado que em algumas ocasiões os resultados apresentados em outros trabalhos não se encontram dentro do intervalo das informações a priori apresentadas no presente trabalho. O número limitado de inventários florestais usados nesse estudo, levando em consideração a dimensão territorial da Amazônia Legal, pode ter influenciado nesse resultado. Uma vez que, a intensidade amostral influencia diretamente os resultados obtidos pelo cálculo de estrutura horizontal da floresta [@augustynczik2011]. Isto pode também indicar uma fragilidade para estes indicadores. No entanto, os indicadores referentes a frequência relativa, dominância relativa e densidade relativa, são fundamentais para a metodologia. Visto que, o conhecimento da composição florística e da estrutura da vegetação são fundamentais para se compreender a dinâmica ecológica do povoamento, assim como a dinâmica da população de diferentes espécies, informações essas fundamentais para a elaboração de um manejo eficiente [@gama2002, @castro2014].

O índice de Payandeh, empregado para determinar o grau de distribuição das espécies citadas por de Lima, et al. (2022), em alguns casos, apresentou resultados diferentes do esperado. De acordo com o valor obtido para Bertholletia excelsa, a espécie apresenta distribuição aleatória, no entanto, de acordo com os autores e Carvalho (1992) e Almeida, et al. (2012) a distribuição dessa espécie ocorre de forma agrupada, sendo o mesmo observado para as espécies Dinizia excelsa [@miron2021], Goupia glabra [@guedes2016], Minquartia guianensis [@almeida2012], Couratari guianensis, Manilkara huberi [@rodrigues2021]. O baixo número de inventários florestais quando comparado a área total no qual o presente estudo abrange, pode ser responsável por essa diferença. Em contrapartida, as espécies Caryocar villosum [@correa2015], Dipteryx odorata [@oliveira2021] apresentaram resultados compatíveis com a literatura. O índice de Payandeh também apresenta sensibilidade para o tamanho da unidade amostral. 

O valor do coeficiente angular (β1) encontrado pela Regra de Reineke foi superior ao descrito por Reineke (1933), como uma constante de -1,605. Isso porque, o β1 obtido pelo modelo pode sofrer alterações em seu valor quando submetido a variações de espécies e idade [@delRei2001].  O ponto chave desse modelo se dá pela sua capacidade de manter o valor do coeficiente angular constante ao ser ajustado em áreas com fitofisionomia semelhantes. Ao comparar os coeficientes do modelo ajustado, foi observado um valor constante referente ao intercepto. O presente trabalho utiliza como inputs dados de diferentes tipos de vegetações presentes na área da Amazonia Legal, no qual obteve um valor médio do intercepto semelhante ao encontrado em um plantio de Eucalyptus saligna Smith [@schneider2011], povoamento Inequiânea de Araucária [@costa2016] e em área de floresta subtropical perene [@long2022]. Tais resultados sugerem que assim como o coeficiente angular, o valor do intercepto obtido pelo ajuste do modelo também pode ser utilizado na metodologia como um indicador de conformidade. 

A análise de diversidade alfa apresentou valor médio de 3,84 para o índice de Shannon – Wiener (H′), que representa o grau de diversidade observado no ambiente. Valor já esperado, isso porque, a região se encontra em área de floresta tropical, onde são observados índices de Shannon – Wiener variando entre 3,83 e 5,85 devido à grande diversidade de espécies [@knight1975, @andrade2015]. O índice de Simpson (D), que também indica o nível de diversidade do ambiente, no entanto, é pouco influenciado por espécies raras, foi de 0,95, muito próximo de 1, demonstrando uma menor dominância de espécies raras sobre o ambiente [@araujo2018]. Por fim, a Equabilidade de Pielou (J), que representa o quão uniforme as espécies estão distribuídas na comunidade e igualmente ao índice de D, se limita a um intervalo entre 0-1, foi de 0,85, indicando uniformidade relativamente alta de indivíduos entre as espécies. Resultado semelhante ao encontrado por Silva et al. (2015), no qual obtiveram J = 0,88, para a região da Amazônia.

A detecção de outliers nos valores do diâmetro a altura do peito das espécies citadas por de Lima et al. (2022), apresentou resultados consistentes em sua distribuição, classificada como t de Student. O alto valor no desvio padrão observado pode estar associado a variedade de ecossistemas e vegetações amostrados no conjunto de inventários florestais. No entanto, o alto valor de desvio padrão não inviabiliza a aplicação deste indicador aos dados, visto que, uma forma muito utilizada para a retirada de madeira de alto valor econômico com volumes acima do autorizado de forma “legal”, é por meio de superestimativas de valores coletados em campo e apresentados ao órgão competente para a obtenção do Documento de Origem Florestal. Essa manobra, permite a legalização de madeira retiradas acima do volume autorizado [@brancalion2018]. Somente no ano de 2022, foram emitidas no Sistema Nacional de Controle da Origem dos Produtos florestais (SINAFLOR), 814 autorizações e cadastradas 858 solicitações de Plano de Manejo Florestal Sustentável (PMFS) em regiões pertencentes a área administrativa da Amazônia Legal, abrangendo um total de 5.3 mil hectares de floresta. Além disso, até o ano de 2022, existiam 17 PMFS em operação sob supervisão do IBAMA, localizados nos estados do Pará, Rondônia, Amapá e Acre (RESPOSTA EMAIL).

Devido as características presentes na região da Amazônia legal, em conjunto com os baixos recursos que os órgãos responsáveis por essa tarefa possuem, torna-se inviável a realização de fiscalizações e auditorias *in loco* com regularidade e frequência adequada em todas as áreas de PMFS [@stone1998, @dittmar2011]. Situação agradava pelo alto número de solicitações de elaboração de PMFS cadastradas todos os anos no SINAFLOR. Em vista disso, a metodologia apresentada nesse trabalho, capaz de identificar não conformidades em dados de inventários florestais, por meio da análise e aplicação de métodos estatísticos, é uma excelente alternativa para o cenário atualmente enfrentado pelos órgãos responsáveis por essa tarefa.

Em razão do grande número de solicitações de PMFS submetidos e analisados todos os anos pelo IBAMA, o torna detentor de um importante e valioso banco de dados no qual a metodologia pode ser empregada. Auxiliando-o em tomadas de decisões e posteriormente no processo de elaboração de pareceres técnicos. Visto que, com base nessas análises o auditor responsável pode inferir previamente a respeito da conformidade do inventário florestal apresentado, evitando um eventual deslocamento de uma equipe de campo, ou as enviando apenas para as áreas em que o inventário tenha apresentado indícios de não conformidade. Ampliando a área de cobertura dos órgãos responsáveis pela fiscalização, facilitando assim a ação do governo no combate às irregularidades. 

Sendo de extrema importância para o cenário atual, onde é visto a retomada dos investimentos no Fundo Amazônia, responsável por financiar projetos que possuam potencial para auxiliar na diminuição de emissão de gases poluentes resultantes do desmatamento, pesquisas relacionadas ao ordenamento territorial, apoio às comunidades indígenas que vivem na Amazônia brasileira, dentre outros projetos [@bndes2023]. No qual havia parado de receber investimentos devido a insatisfação dos principais investidores com a política ambiental do antigo governo [@marcovitch2020].No entanto, cabe ressaltar que a mesma possui certas limitações, devido ao baixo número de inventários utilizados como inputs para a geração das informações a priori, uma vez que quanto maior o número de informações utilizadas em uma análise maior tem de a ser a precisão dos resultados apresentados.
